name: "🚀 Feature Request"
description: Suggest an idea for this project
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: what-feature
    attributes:
      label: What feature would you like to see?
      description: A clear and concise description of what you want to happen.
      placeholder: I'd like to see...
    validations:
      required: true
  - type: textarea
    id: why-feature
    attributes:
      label: Why is this feature valuable?
      description: Explain why this feature would be useful
      placeholder: This would help with...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives you've considered
      description: Any alternative solutions or features you've considered
      placeholder: I've thought about...
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the feature request here
    validations:
      required: false
